version: "3.9"

services:

  postgres:
    image: postgres:17
    container_name: enterprise-postgres

    environment:
      POSTGRES_DB: enterprise_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/project-platform

    container_name: enterprise-backend

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/enterprise_platform
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123

  frontend:
    build:
      context: ./frontend

    container_name: enterprise-frontend

    depends_on:
      - backend

    ports:
      - "5173:5173"

    environment:
      VITE_API_URL: http://backend:8080

volumes:
  postgres_data: