import { useEffect, useState } from "react";
import {
    Box,
    Card,
    CardContent,
    Grid,
    Typography,
    List,
    ListItem,
    ListItemText,
    Alert,
    TextField,
    Button
} from "@mui/material";

import PsychologyIcon from "@mui/icons-material/Psychology";
import WarningIcon from "@mui/icons-material/Warning";
import CheckCircleIcon from "@mui/icons-material/CheckCircle";
import LightbulbIcon from "@mui/icons-material/Lightbulb";

import Navbar from "../components/Navbar";
import api from "../services/api";

function AICopilot() {
    const [insight, setInsight] = useState(null);
    const [error, setError] = useState("");
    const [question, setQuestion] = useState("");
    const [answer, setAnswer] = useState("");
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        fetchAIInsights();
    }, []);

    const fetchAIInsights = async () => {
        try {
            const response = await api.get("/api/ai/insights");
            setInsight(response.data);
        } catch (error) {
            console.error("Failed to fetch AI insights", error);
            setError("Failed to load AI insights.");
        }
    };

    const askAI = async () => {
        if (!question.trim()) return;

        try {
            setLoading(true);
            setAnswer("");

            const response = await api.post("/api/ai/chat", {
                question: question
            });

            setAnswer(response.data.answer);
        } catch (error) {
            console.error("Failed to ask AI", error);
            setAnswer("Failed to get AI response.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <div>
            <Navbar />

            <Box sx={{ padding: 4 }}>
                <Typography variant="h4" gutterBottom>
                    AI Copilot
                </Typography>

                <Typography color="text.secondary" sx={{ marginBottom: 4 }}>
                    AI-powered delivery insights generated by the backend AI service.
                </Typography>

                {error && (
                    <Alert severity="error" sx={{ marginBottom: 3 }}>
                        {error}
                    </Alert>
                )}

                {insight ? (
                    <>
                        <Card elevation={4} sx={{ marginBottom: 4, backgroundColor: "#f5f7ff" }}>
                            <CardContent>
                                <Typography variant="h5" gutterBottom>
                                    Executive Summary
                                </Typography>

                                <Typography variant="body1">
                                    {insight.executiveSummary}
                                </Typography>
                            </CardContent>
                        </Card>

                        <Grid container spacing={3} sx={{ marginBottom: 4 }}>
                            <AICard
                                icon={<PsychologyIcon fontSize="large" />}
                                title="Project Health"
                                value={`${insight.healthScore}%`}
                                description="Calculated from completion, blocked work, and priority workload."
                            />

                            <AICard
                                icon={<CheckCircleIcon fontSize="large" />}
                                title="Sprint Summary"
                                value="Live Summary"
                                description={insight.sprintSummary}
                            />

                            <AICard
                                icon={<WarningIcon fontSize="large" />}
                                title="Risk Level"
                                value={insight.riskLevel}
                                description="Risk level generated from task and project delivery signals."
                            />

                            <AICard
                                icon={<LightbulbIcon fontSize="large" />}
                                title="AI Engine"
                                value="Active"
                                description="Insights generated from backend project and task data."
                            />
                        </Grid>

                        <Grid container spacing={3} sx={{ marginBottom: 4 }}>
                            <Grid item xs={12} md={6}>
                                <Card elevation={4}>
                                    <CardContent>
                                        <Typography variant="h5" gutterBottom>
                                            Detected Risks
                                        </Typography>

                                        <List>
                                            {insight.risks.map((risk, index) => (
                                                <ListItem key={index}>
                                                    <ListItemText primary={risk} />
                                                </ListItem>
                                            ))}
                                        </List>
                                    </CardContent>
                                </Card>
                            </Grid>

                            <Grid item xs={12} md={6}>
                                <Card elevation={4}>
                                    <CardContent>
                                        <Typography variant="h5" gutterBottom>
                                            AI Recommendations
                                        </Typography>

                                        <List>
                                            {insight.recommendations.map((recommendation, index) => (
                                                <ListItem key={index}>
                                                    <ListItemText primary={recommendation} />
                                                </ListItem>
                                            ))}
                                        </List>
                                    </CardContent>
                                </Card>
                            </Grid>
                        </Grid>

                        <Card elevation={4}>
                            <CardContent>
                                <Typography variant="h5" gutterBottom>
                                    Ask AI
                                </Typography>

                                <TextField
                                    fullWidth
                                    label="Ask about your projects, tasks, risks, or sprint"
                                    value={question}
                                    onChange={(e) => setQuestion(e.target.value)}
                                    sx={{ marginBottom: 2 }}
                                />

                                <Button
                                    variant="contained"
                                    onClick={askAI}
                                    disabled={loading}
                                >
                                    {loading ? "Thinking..." : "Ask AI"}
                                </Button>

                                {answer && (
                                    <Box sx={{ marginTop: 3 }}>
                                        <Typography variant="h6">
                                            AI Response
                                        </Typography>

                                        <Box sx={{ marginTop: 1 }}>
                                            {answer.split("\n").map((line, index) => (
                                                <Typography key={index} sx={{ marginBottom: 1 }}>
                                                    {line}
                                                </Typography>
                                            ))}
                                        </Box>
                                    </Box>
                                )}
                            </CardContent>
                        </Card>
                    </>
                ) : (
                    <Typography>Loading AI insights...</Typography>
                )}
            </Box>
        </div>
    );
}

function AICard({ icon, title, value, description }) {
    return (
        <Grid item xs={12} sm={6} md={3}>
            <Card elevation={4}>
                <CardContent>
                    <Box sx={{ marginBottom: 2 }}>
                        {icon}
                    </Box>

                    <Typography variant="h6" color="text.secondary">
                        {title}
                    </Typography>

                    <Typography variant="h5" sx={{ marginTop: 1, marginBottom: 1 }}>
                        {value}
                    </Typography>

                    <Typography color="text.secondary">
                        {description}
                    </Typography>
                </CardContent>
            </Card>
        </Grid>
    );
}

export default AICopilot;